name: Mamual1
runs-on::
  workflow_dispatch:            # 수동 실행 이벤트
    inputs:
      greeting:                 # 입력 파라미터명
        type: string
        default: World          # 입력 파라미터 필수 여부
        required: true
        description: A cheerful World
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello", ${{ github.event.input.greeting }:
